# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.X
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Debug
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: Grate-Test #.zip will be added automatically
        path: Grate/bin/Debug/netstandard2.1/Grate.dll

    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{secrets.WEBOOK}}
        filename: https://github.com/${{ github.repository }}/suites/${check_suite_id}/artifacts/${artifact_id}
        embed-title: ${{ github.event.head_commit.message }}
        embed-footer-text: ${{ github.event.head_commit.author.name }}
        embed-color: 15430476
